{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 67031,
          "sha512": "12f6d7d61989dddd1a93a4a8f65cb85b5fbbfa8ade4e5ec24e83cdc0d27aef043df79d641243563c1f6356572f748f009e7557152be9d1b720b3bb0a6aba222c",
          "sha256": "f5d3db47184aa23c81e269c862abf1658bfb4867a0ec59eee689ce3ad5b304b3",
          "sha1": "98e519b7e672a2000a01e88b67b621ef2b7b6bb2",
          "md5": "3046c3e56d2fa2a4ba8cfb17b40cca49"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-e76c956498841e1ab458577d3892003e553e4f3c"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 67031,
          "sha512": "12f6d7d61989dddd1a93a4a8f65cb85b5fbbfa8ade4e5ec24e83cdc0d27aef043df79d641243563c1f6356572f748f009e7557152be9d1b720b3bb0a6aba222c",
          "sha256": "f5d3db47184aa23c81e269c862abf1658bfb4867a0ec59eee689ce3ad5b304b3",
          "sha1": "98e519b7e672a2000a01e88b67b621ef2b7b6bb2",
          "md5": "3046c3e56d2fa2a4ba8cfb17b40cca49"
        }
      ]
    }
  ]
}
